// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FootyScorer {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FootyScorer.StringResource", typeof(StringResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        internal static string BackLabel {
            get {
                return ResourceManager.GetString("BackLabel", resourceCulture);
            }
        }
        
        internal static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        internal static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        internal static string FinishLabel {
            get {
                return ResourceManager.GetString("FinishLabel", resourceCulture);
            }
        }
        
        internal static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        internal static string MatchPageTitle {
            get {
                return ResourceManager.GetString("MatchPageTitle", resourceCulture);
            }
        }
        
        internal static string NewMatchTitle {
            get {
                return ResourceManager.GetString("NewMatchTitle", resourceCulture);
            }
        }
        
        internal static string NewMatchButton {
            get {
                return ResourceManager.GetString("NewMatchButton", resourceCulture);
            }
        }
        
        internal static string NoRecentLabel {
            get {
                return ResourceManager.GetString("NoRecentLabel", resourceCulture);
            }
        }
        
        internal static string ViewMoreLabel {
            get {
                return ResourceManager.GetString("ViewMoreLabel", resourceCulture);
            }
        }
        
        internal static string RecentLabel {
            get {
                return ResourceManager.GetString("RecentLabel", resourceCulture);
            }
        }
        
        internal static string MatchOnlyLabel {
            get {
                return ResourceManager.GetString("MatchOnlyLabel", resourceCulture);
            }
        }
        
        internal static string IntroLabelText {
            get {
                return ResourceManager.GetString("IntroLabelText", resourceCulture);
            }
        }
        
        internal static string NextLabel {
            get {
                return ResourceManager.GetString("NextLabel", resourceCulture);
            }
        }
        
        internal static string DrawnLabel {
            get {
                return ResourceManager.GetString("DrawnLabel", resourceCulture);
            }
        }
        
        internal static string DefeatedLabel {
            get {
                return ResourceManager.GetString("DefeatedLabel", resourceCulture);
            }
        }
        
        internal static string DefeatedByLabel {
            get {
                return ResourceManager.GetString("DefeatedByLabel", resourceCulture);
            }
        }
        
        internal static string VersusLabel {
            get {
                return ResourceManager.GetString("VersusLabel", resourceCulture);
            }
        }
        
        internal static string ScoreToLabel {
            get {
                return ResourceManager.GetString("ScoreToLabel", resourceCulture);
            }
        }
    }
}
